spring.application.name=Redis-Guardrail-Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=user
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=update

spring.redis.host=localhost
spring.redis.port=6379
